---
name: Deploy to Production
on:
  push:
    branches:
      - master
permissions: read-all
jobs:
  prepare-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build, Tag, and Push Images
        run: |
          # Ensure your script uses the Vultr Registry URL for tagging
          cd ./src/ops/
          chmod +x ./prepare_images.sh
          ./prepare_images.sh
        env:
          registry_url: ${{ secrets.VULTR_REGISTRY_URL }}
          registry_username: ${{ secrets.VULTR_USERNAME }}
          registry_password: ${{ secrets.VULTR_API_KEY }}

  deploy:
    needs: prepare-images
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/chessmine || exit
            
            # Update the code on the server
            git pull origin master
            
            docker login ${{ secrets.VULTR_REGISTRY_URL }} -u ${{ secrets.VULTR_USERNAME }} -p ${{ secrets.VULTR_API_KEY }}

            cd ./src/ops/
            chmod +x spin_up.sh
            ./spin_up.sh prod soft